name = "WarJayPack"
author = "doublej472"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dcf67b99eb7a1bee0ef431dfb9ef482cb31cda6b32cb3269d2af2e13f259a43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.79"
